In [1]:
import re 
import numpy as np
string='bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result=re.findall('b[ao]t',string)
print(result)

['bat', 'bot']


In [2]:
def l2_dist(a,b):
    result=((a-b)*(a-b)).sum()
    result=result**0.5
    return result

In [3]:
a=np.random.rand(20,20)
b=np.random.rand(20,20)

In [4]:
l2_dist(np.reshape(a,(20*20)),np.reshape(b,(20*20,1)))

162.70517981584445

In [5]:
l2_dist(np.reshape(a,(20*20)),np.reshape(b,(20*20)))

8.102702405012081

In [6]:
l2_dist(a.T,b.T)

8.102702405012081

In [7]:
l2_dist(a,b)

8.102702405012081

In [8]:
a1=np.random.rand(4)
a2=np.random.rand(4,1)
a3=np.array([1,2,3,4])
a4=np.arange(1,4,1)
a5=np.linspace(1,4,4)

In [9]:
a3.shape==a4.shape

False

In [10]:
a1.shape==a2.shape

False

In [11]:
a5.shape==a1.shape

True

In [12]:
old=np.array([[1,1,1],[1,1,1]])
new=old

In [13]:
new[0,:2]=0

In [14]:
new

array([[0, 0, 1],
       [1, 1, 1]])

In [15]:
print(old)

[[0 0 1]
 [1 1 1]]


In [16]:
m=np.arange(36).reshape(6,6)

In [17]:
m[2:4,2:4]

array([[14, 15],
       [20, 21]])